### ISSUE TITLE
Add Firewall patch in order to be able to connect to AsTeRICS-Ergo from remote Tablet/Smartphone

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Ergo#101]
Currently Windows 10 by default blocks traffic needed for AsTeRICS-Ergo to work on a remote Smartphone/Tablet. I wrote this patch:
[fixfirewall.zip](https://github.com/asterics/AsTeRICS-Ergo/files/1437412/fixfirewall.zip)
which deletes blocking Java-Firewall-Rules and adds a a rule for the needed ports of AsTeRICS-Ergo.

This patch could be included similar to the FS20-patch to be started from the webapp with UAC-control dialog afterwards. A good place to start this patch would be in the FAQ-question where we describe how to use AsTeRICS-Ergo on a Smartphone/Tablet.

**Comment by klues** [comment]
for the exe-release this fix should be the right one:
[fixfirewall2.zip](https://github.com/asterics/AsTeRICS-Ergo/files/1437822/fixfirewall2.zip)
it disables the rules for "asterics ergo.exe" and not for java in general.

**Comment by klues** [comment]
in order to also support Edge/IE for showing the correct local IP in the Smartphone-FAQ, we maybe could add a REST-method that returns the current local IP, with some snippet like this:
```
Enumeration< NetworkInterface > interfaces = NetworkInterface.getNetworkInterfaces( );
List<NetworkInterface> list = new ArrayList<>();
while(interfaces.hasMoreElements()) {
    NetworkInterface element = interfaces.nextElement();
    if(element.isUp() && element.getName().startsWith("wlan")) {
        list.add(element);
    }
}
list.get(0).getInetAddresses();
```

**Comment by deinhofer** [comment]
Think about executing it in the installer run section: http://www.jrsoftware.org/ishelp/index.php?topic=runsection

Regarding fetching the IP address:
Yes this is a good idea. But the script should not only show IPs of WLANs as wired ones could be also used.

**Comment by klues** [comment]
@ run in installer:
yes, good idea, better than a manual patch that has to be executed by the user.

@ ip address:
the problem is, that it is not really possible to detect which IP to use if there are more than one active network interfaces (`element.isUp()`). thats why I thought of this "hack" to only use wifi-interfaces, because it will be the right one in most of the cases...
Maybe we can implement something where wifi ip-addresses are prefered and if no wifi is found the next one is used.

**Comment by klues** [comment]
IP-address issue moved to own issue: https://github.com/asterics/AsTeRICS-Ergo/issues/105

**Comment by klues** [comment]
should be fixed with https://github.com/asterics/AsTeRICS-Ergo/commit/3f388275f45ca8e6a9e73ec7d1d4224d8fc9148c
