### ISSUE TITLE
Create info-site for AsTeRICS-Ergo

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Ergo#103]
for the first release of AsTeRICS-Ergo (4.0.0) we need an info page containing:
* general info about AsTeRICS-Ergo
* download-Button (linking to the latest release on github)
* links to the mock-sites of AsTeRICS-Ergo (github.io)
* two languages: german and english

the info-site should also be accessible on github.io. At first the path will be:
https://asterics.github.io/AsTeRICS-Ergo/info/
and the environment control webapp/mock will stay on
https://asterics.github.io/AsTeRICS-Ergo/mock.html and
https://asterics.github.io/AsTeRICS-Ergo/

in the future the current asterics-ergo environmental control will move to
https://asterics.github.io/AsTeRICS-Ergo/webapps/envcontrol/ (or similar)
https://asterics.github.io/AsTeRICS-Ergo/webapps/envcontrol/demo (instead of mock.html)
and on localhost it will be:
https://localhost:8091/webapps/envcontrol/ (or similar)

**Comment by klues** [comment]
created first version of the info-site here:
https://github.com/asterics/AsTeRICS-Ergo/tree/master/custom/bin/ARE/data/webservice/info

looks like this:
https://asterics.github.io/AsTeRICS-Ergo/info/index.html

@stefaniehoechtl @deinhofer 
feel free to add/change anything or make suggestions what we should change/add :)

**Comment by klues** [comment]
feedback from @deinhofer:
* move "introduction info" (project, ...) to bottom of page under "further information"
* Only say that Asterics-Ergo is for environmental control, not for computer control.
* list some possibilites of devices that can be controlled
* link to FAQs and Hardware Assistant under own "help" title
* maybe add "static" versions of FAQs and Hardware-Assistant that do not show Back-Button and Breadcrumbs

**Comment by klues** [comment]
improved info-page with: https://github.com/asterics/AsTeRICS-Ergo/pull/117

changes:
* changed text & structure according to feedback of @deinhofer 
* links to help are now to a different "mode" of asterics ergo, so that no "back" button is shown and a click on the "AsTeRICS Ergo" header links back to the info page -> better integration of FAQ and hardware assistant
* download link is automatically updated, always points to the latest version
* translated info-page to english

see it at https://asterics.github.io/AsTeRICS-Ergo/info/

**Comment by deinhofer** [comment]
todo:
* add impressum link (to asterics-academy) in footer
* footer: AsTeRICS Ergo, mailto:asterics-foundation, Impressum (link to asterics academy foundation)

**Comment by klues** [comment]
did TODOs with https://github.com/asterics/AsTeRICS-Ergo/commit/97aac7ffaea22da5d3bb7a0441025a42ffa91831

see it here:
https://asterics.github.io/AsTeRICS-Ergo/info/index.html

so I'll close this issue.
