### ISSUE TITLE
Version 4.0.0-alpha does not work on Win 8.1 - Browser starts and shows "No Connection"

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Ergo#107]

**Comment by klues** [comment]
case (1): (chris' laptop)
looks like this: http://prntscr.com/h8pc44

**Comment by klues** [comment]
@ case (1):
* AsTeRICS 3.3 works
* also does not work with current master from asterics-ergo repo.

log file says:
`[java] FEIN: Starting REST API at http://0.0.0.0:8091/rest`
but not:
`[java] FEIN: Initializing Websocket...` <-- is shown on Win10 computer, where AsTeRICS-Ergo works

@deinhofer: do you have any idea what the error could be?

**Comment by klues** [comment]
case (2):
I've tried to install AsTeRICS-Ergo 3.3 and 4.0 on a Windows 8 Virtual Machine - both did not work :'(
* at starting with .exe: http://prntscr.com/h8qd1c
* at starting with .bat: http://prntscr.com/h8qbiw

After installing JDK on the virtual machine, the .bat works, the .exe not.

**Comment by deinhofer** [comment]
@case (2):
Are you talking about ARE.exe and start.bat, start_debug.bat?
They all require a normal Java installation on the system. The embedded Java of the native installer is not usable in this case.

But I don't know why the ARE.exe did not work.

**Comment by deinhofer** [comment]
@case (2):
.exe: Probably we have to install the microsoft redistributable: http://www.giga.de/unternehmen/adobe/tipps/loesung-api-ms-win-crt-runtime-l1-1-0.dll-is-missing-fehler/

but I am wondering if this was ever necessary before. Are we talking about 
AsTeRICS Ergo.exe also?

**Comment by klues** [comment]
moved case 2 to https://github.com/asterics/AsTeRICS-Ergo/issues/112

so this issue is just about the empty browser after starting asterics-ergo (see: http://prntscr.com/h8pc44)

**Comment by klues** [comment]
A possible reason for the empty browser page is that building of the release was faulty because of no clean on asterics-repository.
So @deinhofer added a clean to all ant-deploy target with https://github.com/asterics/AsTeRICS/commit/71afc3b63953557dfd5e3c03433c8cabf75eb201 (and other commits on the same day)
this should solve the issue for further releases.
