### ISSUE TITLE
Installation of FS20 fails using Microsoft Edge?

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#109]
Joe’s laptop (Microsoft Windows 10 Home, Acer Aspire E5-772G, McAfee):
AsTeRICS Ergo opens in Microsoft Edge, installation of FS20 fails (tried several times), installation of FS20 works using Firefox.
Everything else works without problem.

**Comment by deinhofer** [comment]
I think at this stage we should set this to a lower priority, let's focus on firefox and chrome for now.

**Comment by stefaniehoechtl** [comment]
Ok, but then we should recommend using Firefox and Chrome. I can add a FAQ.

**Comment by klues** [comment]
> AsTeRICS Ergo opens in Microsoft Edge, installation of FS20 fails (tried several times), installation of FS20 works using Firefox.

how did it fail in Edge?

**Comment by stefaniehoechtl** [comment]
Lamp was not shining after 10 sec ---> I selected "Fix problem" --> "Yes" - but the Test failed
Then I chose another USB-Port – the lamp was shining after 10 sec, but the Test failed
I closed AsTeRICS Ergo and tried again with the second USB-Port - light was shining, but Test failed
I tried a third USB-Port - the light was not shining - I selected "Fix problem", but nothing happened

In Firefox it worked the first time I tried without any problems (lamp was still lit after 10 sec)

**Comment by klues** [comment]
hmm, strange... maybe try it again, when i did the changes I proposed in https://github.com/asterics/AsTeRICS-Ergo/issues/108#issuecomment-344535165 - lets see if the error then still exists.

**Comment by klues** [comment]
@stefaniehoechtl maybe this is also resolved with https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v4.0.0-alpha4 ?!

**Comment by stefaniehoechtl** [comment]
I tested AsTeRICS Ergo v4.0.0-alpha5 on 2 laptops using Microsoft Edge: Installation of FS20 without problems

**Comment by klues** [comment]
ok, cool! :)
then lets close this issue.
