### ISSUE TITLE
Translate AsTeRICS Ergo into English

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#11]
Translate AsTeRICS Ergo into English

**Comment by klues** [comment]
Merged https://github.com/asterics/AsTeRICS-Ergo/pull/42 for making FAQs translateable and searchable
see: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/ for testing it
@stefaniehoechtl (or anyone) could now start to translate the FAQs by editing the files: 
* https://github.com/asterics/AsTeRICS-Ergo/blob/master/custom/bin/ARE/data/webservice/angular/envControl/component/help/faq/envControlFaqEn.js
--> here are the titles of the FAQs that need to be translated to english
--> in the field "keywords" you could add keywords for an FAQ, which are also found on search. so if you set e.g. "keywords = ['installation', 'einrichtung'] this FAQ is also found if the user searches for "installation" or "einrichtung".
* https://github.com/asterics/AsTeRICS-Ergo/tree/master/custom/bin/ARE/data/webservice/angular/envControl/component/help/faq/html
--> in this folder all files suffixed with ...en.html need to be translated to english
--> the structure of the files (HTML) should stay the same and only the texts should be changed

**Comment by stefaniehoechtl** [comment]
I tried to translate the questions & anwers. I created new branches, as I do not want to destroy anything. Could you give me Feedback if I did anything wrong and show me how I can do it better?

@klues Based on the last round of our user evaluation, I would like to add some more FAQs. Could you show me how to do that? Could you also show me how I can translate the text of other pages (e.g. IrTrans Installation Wizard)? (Maybe on Monday?)

A friend of mine is married to a native. Maybe she can have a look and iprove the translation...

**Comment by klues** [comment]
@stefaniehoechtl i've merged most of the pull requests - very good work, that was quick! 👍 
you can see and check the result here: https://asterics.github.io/AsTeRICS-Ergo/#!/home/envcontrol/help/faq/ 
yes i'll show you how to translate text on other pages (on monday, or on another day - things we want to do on monday are getting quite much ;))

**Comment by klues** [comment]
I made the rest of AsTeRICS-Ergo translateable in this branch:
https://github.com/asterics/AsTeRICS-Ergo/tree/hoechtl/issue%2311/translate-asterics-ergo

@stefaniehoechtl you could do the translation now by translating everything in https://github.com/asterics/AsTeRICS-Ergo/blob/hoechtl/issue%2311/translate-asterics-ergo/custom/bin/ARE/data/webservice/angular/envControl/i18n/i18n_envControl_en.js
any changes you can directly commit to `hoechtl/issue#11/translate-asterics-ergo` branch (see http://prntscr.com/gt7clq )
everything to be translated has a "EN - " prefix

**Comment by deinhofer** [comment]
translation done, must be merged and quality checked

**Comment by klues** [comment]
merged https://github.com/asterics/AsTeRICS-Ergo/pull/96

**Comment by klues** [comment]
here you can see the current result of the translation:
https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol
@stefaniehoechtl please check once again and maybe contact your friend for checking

**Comment by stefaniehoechtl** [comment]
@klues 
I checked the translation and found the following mistakes:
**Ad Installation of the FS20 system:**
Change _“Installation of the FS20 system0.”_ into --> _“Installation of the FS20 system”_
Change _“The FS20 system was installed successfully. Please select New Device The FS20 system was installed successfully. Please select“_ into --> _„The FS20 system was installed successfully. Please select New Device to set up a control using the FS20 system.“_

Overall the English is not perfect, but I hope it is comprehensible. ;)

**Comment by klues** [comment]
@stefaniehoechtl 
fixed the error with https://github.com/asterics/AsTeRICS-Ergo/pull/104
check it here: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/install/fs20

I will close this issue now, because I think everything is translated.
@stefaniehoechtl if your friend checks the translation and finds some more errors, lets make a new issue to fix them.
