### ISSUE TITLE
AsTeRICS Ergo cannot be opened???

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#110]
Testing with my dad’s laptop (Microsoft Windows Vista Home Premium; VAIO Sony Corporation VGN-FW21M; Avira):
Installation of AsTeRICS Ergo (not) successful? (icon is on Desktop) – opening AsTeRICS Ergo is not possible (error message: “AsTeRICS Ergo.exe – Komponente nicht gefunden Die Anwendung konnte nicht gestartet warden, weil api-ms-win-crt-runtime-l1-1-0.dll nicht gefunden wurde. Neuinstallation der Anwendung könnte das Problem beheben.“)

**Comment by deinhofer** [comment]
This is probably a duplicate of https://github.com/asterics/AsTeRICS-Ergo/issues/112

So closing this one.

**Comment by klues** [comment]
yes, looks like the same...

@stefaniehoechtl please re-try it with https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v4.0.0-alpha2
