### ISSUE TITLE
Error on installation of IrTrans

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#111]
Testing with my mum’s laptop (Windows 10 Home, Medion Akoya E7422 MD99920, Avira): 

When trying to install the IrTrans, the following error message pops up: “Microsoft .NET Framework 2.0 Service Pack 2 (x64) could not be installed. Please use Windows Update to manually install this update on your system. IRTrans Software Setup cannot continue”.

Installation and setting up the control of FS20 devices without any problems.
After restarting the computer, the control of the FS20 devices only works after unplugging and reconnecting the FS20.

Controlling the environment via smartphone fails (error message on smartphone: the website is not accessible)

**Comment by klues** [comment]
ok, the FS20 problem should be the same as in https://github.com/asterics/AsTeRICS-Ergo/issues/108
moved the smartphone problem to own issue: https://github.com/asterics/AsTeRICS-Ergo/issues/113

regarding the Installation of IrTrans software:
I also had this issue one time.
Try to download .NET framework from here: https://www.microsoft.com/de-DE/download/details.aspx?id=48130 and check if installation of IrTrans then works.
However this is a problem of IrTrans-installation and somehow out of range of our responsibility. We could add a FAQ describing this problem and the solution?!

**Comment by klues** [comment]
i had this issue also on my windows 8 virtual machine.
try to download and install:
https://www.microsoft.com/de-at/download/details.aspx?id=21
in my case it helped.
the link in my previous comment is wrong.

**Comment by stefaniehoechtl** [comment]
Today I tested with AsTeRICS Ergo v4.0.0-alpha3
I had the same error message, so I installed Microsoft .NET Framework 3.5 - now the control of the IrTrans devices works without problem (also after restarting the computer)! :)
So I guess the only solution is adding a FAQ.

**Comment by klues** [comment]
we could also include the installer for .NET Framework 3.5 in the AsTeRICS-Ergo installer, so that it is automatically installed. but I do not know if we want that?!

**Comment by klues** [comment]
@deinhofer what do you think we should do here? FAQ or embed the .NET-Framework installer in AsTeRICS-Ergo installer?

**Comment by deinhofer** [comment]
I'd prefer to create an FAQ entry and alos mention it as possible intermediate step at the installation process for IrTrans. 

I don't want to embed .NET if it is just needed for some very rare cases.

**Comment by klues** [comment]
ok, yes, then lets add a FAQ, I'll do it.

**Comment by klues** [comment]
added FAQ with https://github.com/asterics/AsTeRICS-Ergo/commit/805b1c9f5394a5d661f04070bf2f299bebe7304e

see result
* FAQ: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/faq/42
* Hint in install wizard (point 3): https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/install/irtrans?mockIrConnected=false

so I think we can close this?

**Comment by deinhofer** [comment]
looks good

**Comment by klues** [comment]
ok, then i'll close the issue.
