### ISSUE TITLE
error controlling the environment using the smartphone

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Ergo#113]
Test setup:
AsTeRICS-Ergo v4.0.0-alpha
(Windows 10 Home, Medion Akoya E7422 MD99920, Avira)

Problem:
Controlling the environment via smartphone fails (error message on smartphone: the website is not accessible)

**Comment by klues** [comment]
@stefaniehoechtl question:
did you get any firewall-popups on first time of starting AsTeRICS-Ergo on this computer.

Please also try to go to:
1.  Start Menu -> type "firewall"
2. Open "Windows-Firewall mit erweiterter Sicherheit"
3. go to "eingehende Regeln" http://prntscr.com/h9xa2v
4. do you find rules named "asterics ergo.exe"? if yes are they activated? http://prntscr.com/h9xay7
5. do you find 2 rules named "Open Port xy for AsTeRICS-Ergo"? http://prntscr.com/h9xbgl

**Comment by klues** [comment]
just added a new line in the firewall-skript to also disable rules generated by win8:
https://github.com/asterics/AsTeRICS-Ergo/commit/47811bd16008f3690529eacecd30553615f969f3
so with the next release this maybe fixes the problem.

**Comment by stefaniehoechtl** [comment]
Test setup:
AsTeRICS-Ergo v4.0.0-alpha3
(Windows 10 Home, Medion Akoya E7422 MD99920, Avira)

Now controlling the environment via Smartphone works :)

**Comment by klues** [comment]
yeah :)
so I think we can close this issue.

**Comment by stefaniehoechtl** [comment]
I tested AsTeRICS Ergo v4.0.0-alpha5 on 5 laptops & 1 PC.
I was not able to control the environment via smartphone in any of my tests. There is always the following message on the smartphone: “Not Found - Resource identified by path ‘/’, does not exist.”

(& The address to control the environment via smartphone is not shown using Microsoft Edge & Internet Explorer.)

**Comment by klues** [comment]
oh, after changing the paths with https://github.com/asterics/AsTeRICS-Ergo/issues/92 i forgot to change the links for the smartphone-FAQ. good that you tested it, I'll fix it today.

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Ergo/commit/eeabf75b339e18a396050d5e7300c6c7b0826d19

> & The address to control the environment via smartphone is not shown using Microsoft Edge & Internet Explorer.

yes, in these browsers unfortunately it is currently not possible to get the needed IP address...

**Comment by klues** [comment]
is fixed with https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v4.0.0-alpha6
