### ISSUE TITLE
IrTrans setup wizard - step 4: USB cable

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#12]
**Problem:** 
Some users missed to order an USB-cable. They release this when trying to install IrTrans. However, it is not clear which USB-cable to order.

**Solution:**
Setup IRTrans - step 4: add the exact name of the USB-cable needed (inkl. link to “Help – IrTrans”)

**Issue resolved if:**
The exact name of the USB-cable is added to step 4 of the IrTrans setup wizard & linked to “Help – IrTrans”.

**Comment by klues** [comment]
sieht jetzt so aus: http://prntscr.com/gk7yth und ist damit closed.
siehe https://github.com/asterics/AsTeRICS-Ergo/pull/19
