### ISSUE TITLE
IrTrans Installation Wizard: add autoscroll

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#121]
IrTrans Installation Wizard: When clicking on “Test”, you always need to scroll down to see whether the test was successful, that is a bit confusing --> add autoscroll

**Comment by klues** [comment]
strange: the error only happened in firefox and edge, but autoscroll worked on all other places (where it works in the same way).

however: fixed with https://github.com/asterics/AsTeRICS-Ergo/commit/e2d1402f290e56df5961be01c39d6c79029adefd
