### ISSUE TITLE
Problem with IRTrans udev rule

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS-Ergo#128]
When testing AsTeRICS Ergo in a VirtualBox with Ubuntu 17.10, 
the IRTrans setup did not work correctly (the udev rule for the IRTrans COM Port was created with wrong Vender / Product IDs for the USB device).

After changing the udev rule manually to vendor:0403 / product: fc60 the COM Port was found.
Maybe the reason was that the IDs are not the same for every IRTrans device ?

(maybe it would also make sense to add a delay in the IRTrans start script so that this problem can be identified better)

**Comment by klues** [comment]
should be fixed with asterics-ergo-4.0.1.deb from https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v4.0.0
