### ISSUE TITLE
IrTrans setup wizard - step 3:

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#13]
**IrTrans setup wizard - step 3:**

**Problems:**
* IRTrans Software – InstallAware Wizard - “Selection Options”: it is not clear what to select
* Most participants skim through the text and do not read that they need to think about selecting “Add IRTrans Server to the Startup Folder”

**Solution:**
* Add a screenshot of “Select Options” (IRTrans Software – InstallAware Wizard)? inkl. explanation, that you just need to select “next” and do not need to change the settings --> select “IRTrans Virtual Remote” & select “next”?
* Add a check to “Add IRTrans Server to the Startup Folder”

**Issue resolved if:** 
* "Select Options" is explained
* A check is placed in the box beside "Add IRTrans Server to the Startup Folder"

**Comment by klues** [comment]
habs jetzt mal so gemacht:
http://prntscr.com/gk7lbj

bezüglich den Punkt mit "Select Options": Ich weiß nicht, wollen wir da wirklich noch einen extra Screenshot hinzufügen sollen?! Der Assistent ist eh schon so lange und einen eigenen Screenshot für etwas, wo der User eh nix machen muss, finde ich ein bisschen unnötig, oder?

**Comment by klues** [comment]
stand oben ist mit #19 gemerged, also wenn es passt, kann man das Issue schließen.

**Comment by stefaniehoechtl** [comment]
Finde ich super, so wie du es gemacht hast. ;) Wegen "Select Options": das war für ein paar TN schon sehr verwirrend. Wir müssen es finde ich zumindest erwähnen, dass man da nichts umstellen braucht. Weil es haben einige TN länger überlegt, ob sie hier etwas ändern sollen und 1 hat sogar etwas geändert. Aber ist hald die Frage, ob es nicht noch verwirrender ist, wenn wir es nur beschreiben. Ich dachte, dass hier ein Screenshot vielleicht hilft. Aber ich weiß auch nicht, wie wir es am eindeutigsten gestalten können.

**Comment by klues** [comment]
added screenshot in https://github.com/asterics/AsTeRICS-Ergo/pull/34

**Comment by klues** [comment]
see here for version with new, second screenshot:
https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help/install/irtrans?mockIrConnected=false
