### ISSUE TITLE
IrTrans setup wizard - step 5

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#14]
**IrTrans setup wizard - step 5:**

**Problem:**
Some participants are looking for the symbol for a very long time. They cannot find it, as the installation is already finished, but they keep looking. Therefore some need the information that they can continue with step 6.

**Solution:**
Add the following an explanation: 
“The setup is started automatically. The installation is still in progress, if you can see the icon on the bottom right. If you cannot see the icon, you can presume with step 6.” (last sentence in bold)

**Issue resolved if:**
Step 5 is explained in more detail.

**Comment by klues** [comment]
schaut jetzt so aus:
http://prntscr.com/gk7uug
hab nur den Text bisschen abgeändert und es den letzten Satz fett gemacht.
Passts so, oder sollen wir es anders machen?

**Comment by klues** [comment]
stand oben ist mit https://github.com/asterics/AsTeRICS-Ergo/pull/19 gemerged, also wenn es passt, kann man das Issue schließen.

**Comment by stefaniehoechtl** [comment]
Finde ich gut :)
