### ISSUE TITLE
IrTrans setup wizard - step 6

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#15]
**IrTrans setup wizard - step 6:**

**Problem:** 
-	It is not clear where „start“ is.
-	The user cannot see the picture when searching for “IRTransServer USB”.

**Solution:** 
-	Add an arrow pointing towards “start” (on the picture).
-	Move the picture to the right.

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Ergo/pull/18
result: http://prntscr.com/gk7514
