### ISSUE TITLE
add auto scroll to the hardware wizard

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#2]
**Problem**:
Some participants use the hardware wizard and select the devices which they would like to control, but do not see the recommended hardware.

**Solution**: 

- Explain the hardware wizard
- Add auto scroll

**Issue is resolved if**:

- The hardware wizard is explained, e.g. "please select the devices which you would like to control using AsTeRICS Ergo. Afterwards you can see the required hardware to control these devices below."
- The recommended hardware is shown when selecting a device.

**Comment by klues** [comment]
see: https://prnt.sc/gk9t3m
resolved with https://github.com/asterics/AsTeRICS-Ergo/pull/25

**Comment by klues** [comment]
habs jetzt wie oben im video zu sehen gemacht. Was meint ihr, passt das so? Ich hab jetzt keinen neuen Text hinzugefügt (Text liest ja eh keiner). Ich hoffe so, wie es ist, mit dem Runterspringen und der Animation sollte es eh klar sein, wie das Ganze funktioniert, oder?

**Comment by stefaniehoechtl** [comment]
Super gemacht. :) Das mit der Erklärung war ein Wunsch von ein paar TN. Lassen wir es vorerst einfach mal so. Ein paar TN hätten sich schon eine Erkläung gewünscht. Es sind allgemein auch ein paar Sachen gefallen, die sie gerne zusäztlich erklärt oder für sie verständlicher formuliert hätten. Bei der Übersetzung ins Englische schau ich eh auch, ob sie sich nicht auch Änderungen auf der deutschen Seite gewünscht hätten, dann kann ich ev. auch hier noch eine kurze Erklärung ergänzen. ;)

**Comment by klues** [comment]
ok, then I close the issue.
(Martin said we should write everything in English, so I'll do that ;))
