### ISSUE TITLE
Change port numbers of AsTeRICS Ergo

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Ergo#23]
**Problem**

When starting the ARE of Asterics or any other Asterics based project e.g. a standalone camera mouse, the same ports for the webservices (8081, 8082) are used.
But there are use cases where both instances should run independently, e.g. when Asterics Ergo should be used for environmental control and the Asterics camera mouse as input device.

**Solution**
A simple fix would be to change the port numbers of Asterics Ergo to something else (hardcoded),e.g.
8091, 8092

This also depends on a central specification of Asterics ports and a more sophisticated algorithm in the Asterics master branch.

**Comment by deinhofer** [comment]
@deinhofe: makes webservice ports configurable in Asterics master repository.
Asterics Ergo will then use hardcoded ports at: 8091?, 8092?

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Ergo/pull/89
port numbers are now:
REST: 9081
websocket: 9082

**Comment by deinhofer** [comment]
Great!

Just one favour: change it to 
8091
8092
as suggested in the comment above.

The reason is the following:
Due to APE it will be possible that several instances of ARE run on the same machine e.g. normal ARE, Asterics Ergo, Camera Mouse,...
They all need there dedicated ports. So I thought about numbering scheme which starts at

8081-8090 for the normal ARE
8091-8100 for AstErICS Ergo
8101-8110 for another instance,....

so each application has a fixed decade of numbers.

There could be an algorithm trying numbers and increasing them by 10 to get a next try.
On the other hand, if the port numbers of asterics ergo are 9081-9082 they would very unlikely collide with the rest...

**Comment by klues** [comment]
ok, changed it to 8091 and 8092 with https://github.com/asterics/AsTeRICS-Ergo/pull/91
