### ISSUE TITLE
Disclaimer text should exclude controlling vehicles (e.g. wheelchairs)

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Ergo#24]
**Problem**

AsTeRICS Ergo must not be used to control vehicles e.g. a wheelchair. The disclaimer text should state this explicitely!

**Solution**
Extend disclaimer text in web UI

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Ergo/pull/26
now looks like this:
http://prntscr.com/gkkp7m
http://prntscr.com/gkkpc1

**Comment by deinhofer** [comment]
great! :+1:
