### ISSUE TITLE
Intervisibility: IrTrans - device

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#27]
**Problem:**
Sometimes controlling a device is not possible, as the IrTrans is covered. It is not clear which part of IrTrans needs to point towards the device and that intervisibility is needed.

**Solution:**
•	Add an explanation, e.g. to be able to control the device, ensure that there is intervisibility between the IrTrans and the device.
•	Add a picture, which shows which part of the IrTrans needs to point towards the device.
I think this information should pop up after the user set up the control of a new IR device (--> in the wizard for setting up an IR device, e.g. TV, radio).

**Comment by klues** [comment]
Will be solved with this changes:
* replacing normal ir-trans-picture here: http://prntscr.com/gsdb04 with a picture where IrTrans + Remote control are seen
* after finishing the add-ir-assistant a message like this: http://prntscr.com/gsdciy will be shown (success message) which tells the user, that he now must point irTrans at the device (+ picture maybe)

**Comment by klues** [comment]
hopefully fixed with https://github.com/asterics/AsTeRICS-Ergo/pull/95 :
* after adding an IrTrans-device a success message is shown
* IrTrans-Assistants show picture with irtrans+remote control
see: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/add/amblight/
