### ISSUE TITLE
room lighting: replacing the conventional light bulb with the IR bulb

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#28]
**Problem:** 
It is not clear when to replace the conventional light bulb with the IR bulb

**Solution:**
Add an explanation in the wizard for setting up the control of the room lighting

**Comment by klues** [comment]
fixed with: https://github.com/asterics/AsTeRICS-Ergo/pull/36
see: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/add/amblight/
