### ISSUE TITLE
add USB cable to hardware wizard

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#3]
**Problem:**
It is not clear that an USB cable is needed to control IR-devices (connection IrTrans - computer)

**Solution:**
Add an USB cable (+ picture) to the hardware wizard 

**Issure resolved if:**
The hardware wizard also recommends ordering an USB cable if an IR device is selected.

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Ergo/pull/94
see https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol
