### ISSUE TITLE
editing mode and user mode

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#39]
One participant recommends setting up an editing mode and an user mode, in order that the user cannot make accidential changes.

**Comment by deinhofer** [comment]
This could be very important for cognitive disability or to prevent deleting buttons accidently by a user with motor impairment.

**Comment by klues** [comment]
duplicate of https://github.com/asterics/AsTeRICS-Ergo/issues/87 -> closed
