### ISSUE TITLE
add other devices to the hardware wizard

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#4]
**Problem:**
Users might want to control other devices than the examples given in the hardware wizard. However, the hardware wizard does not take them into account, so it is not clear which hardware they need.

**Solution:**
Add “other device controlled by IR remote” and “other device which is plugged into an outlet” to the hardware wizard

**Issure resolved if:**
Apart from the examples given in the hardware wizard (e.g. radio, television), you can also select „other device controlled by IR remote” and “other device, which is plugged into an outlet”. Selecting these should also influences the hardware recommendations.

**Comment by klues** [comment]
see: https://prnt.sc/gk9t3m
resolved with https://github.com/asterics/AsTeRICS-Ergo/pull/25
