### ISSUE TITLE
Test report AsTeRICS Ergo Version 3.2.1 Windows 10

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#40]
**Acer - Windows 10
AsTeRICS Ergo Version 3.2.1**

**_Detailed description:_**
Download successful.
**I want to open the installation file, however, a window pops up which states that the execution of this app might be a risk for the PC.** As user I would be suspicious.
I decide to continue anyway. 
I open “AsTeRICS Ergo”. The Hardware wizard is working properly. 
**I select „New Device“ – „Table / Floor-Lamp“: the examination, whether the FS20 system is installed, does not stop** (FS20 is not plugged in)
I go back and select “New Device” – “Radio / CD player”: I am asked whether I have already purchased the IrTrans – I select yes.
I am transferred to the **IrTrans Installation Wizard**: I follow the instructions (I do not know whether all users would know where to find the setup file), **at the end of the page I select “test” – however the program does not stop testing**
**I go back and select “New Device” – “Radio / CD player”: the examination whether the IrTrans is installed does not stop (IrTrans is plugged in)**
I go back, unplug the IrTrans and select “New Device” – “radio / CD player”: the examination whether the IrTrans is installed does not stop
**I restart AsTeRICS Ergo and try various wizards: the examinations whether IrTrans or FS20 are installed do not stop**
I restart the computer, open AsTeRICS Ergo and select „New Device“ – „Table / Floor-Lamp“: the examination whether the FS20 system is installed does not stop (FS20 is not plugged in)
I go back and select “New device” – “Television” – the examination works, I am asked whether I have already bought an IrTrans. I say yes. Now the Installations Wizard appears. The user would be confused, as he has already installed the IrTrans.
The user might just plug in the IrTrans and select “test”, but the test fails. So I guess the user would start all over again… so I follow the instructions again and open the setup file. The program says I should restart the computer, so I do that. 
Afterwards I open AsTeRICS Ergo and need to start all over again with “New Device” – “Television” – I have already bought the IrTrans – I am transferred to the set up wizard for IrTrans – I download the  Software IrTrans USB – open the setup file – I plug it in – step 6: I search for “IrTransServer USB”, but it cannot be found!
--> From here on the user would not get on!
I uninstall the IrTrans Software and start again with opening AsTeRICS Ergo - “New Device” – “Television” – I am asked whether I have already bought an IrTrans – I say yes. I follow the instructions –  in the end I select “test” – however, the program does not stop testing.
I go back and select “New Device” – “Television”: the program does not stop examining whether the IrTrans is installed.
I uninstall IrTrans, delete the setup file and restart the computer.
I do everything again – however, at the end of the IrTrans setup wizard, it does not stop testing.
I go back and select help – installation of the hardware – Installation IrTrans – the examination whether the IrTrans is installed does not stop.
I go back and choose installation FS20: the examination whether the FS20 is installed does not stop.
I plug in the FS20, a window opens saying that the installation was successful, however, the examination whether the FS20 is installed does not stop.

**--> It is not possible to install the IrTrans or the FS20 system.**

_**Errors:**_
-	**When trying to open the installation file, a window pops up which states that there might be a risk for the PC.**
-	**“New Device” – “Table / Floor Lamp”: the examination, whether the FS20 system is installed, does not stop**
-	**IrTrans Installation Wizard: I follow the instructions and select “test” at the end of the page – however, the IrTrans does not stop testing, whether the installation was successful**
-	**“New Device” – e.g. “Radio / CD player”: the examination whether the IrTrans is installed does not stop**

Do you have any suggestions?

**Comment by deinhofer** [comment]
The window popup is probably related to the virus scanner false positive problem: 
#20

Regarding the hanging HW tests, similar things have already been observed here:
#21

So, if we are lucky and fix the two issues above, there might be a chance that this issue is fixed as well.

**Comment by stefaniehoechtl** [comment]
Thank you for the tip.

**_Detailed report of further testing (short summary see below):_**
**I disable the protection of my virus scanner (I use Kaspersky).**
I open AsTeRICS Ergo and select „New Device“ – „Table / Floor Lamp“. **The examination whether the FS20 is already installed works.** I am asked whether I have already bought FS20 – I select “yes”. 
**Installation FS20 wizard: after 10 sec, the lamp is not lit anymore, the test fails.**
I go back and select “New Device” – “More..” – “Remote – device”: The examination whether the IrTrans is already installed works. I am asked whether I have already bought the IrTrans – I select “yes”. I follow the instructions in the **IrTrans Installation Wizard – the test is successful.** 
**I set up the control of the robot vacuum cleaner successfully** (inkl. commands “start”, “stop” & “homing”). 
I **restart the Computer. A window pops up, which states “Error starting IRServer”. This message might confuse the users. (It pops up every time I restart the PC).**
I start AsTeRICS Ergo, the control of the robot vacuum cleaner works, however, the **command “homing” is gone. I delete the vacuum cleaner and relearn everything – however, now I have the commands “start” & "stop" twice.** **I restart the PC and open AsTeRICS Ergo – however my device “vacuum cleaner” is not there anymore.** I add the control of the vacuum cleaner again inkl. the commands “start”, “stop” & “homing”. I can control the vacuum cleaner using AsTeRICS Ergo. I restart the PC. I start “AsTeRICS Ergo” – I can control the vacuum cleaner as intended. I add the commands “right”, “left”, “forwards” & “backwards” and close AsTeRICS Ergo. **I restart the Computer & start “AsTeRICS Ergo”. The vacuum cleaner is gone.** I add the vacuum cleaner inkl. The commands “start”, “stop” & “homing”. **I delete the vacuum cleaner. I add the vacuum cleaner inkl. the commands “start”, “stop” & “homing” again. I have the vacuum cleaner, but every command twice.** I delete 3 commands, so I have every command once.
I add ambient light and name it “living room”. I learn “on” and “off”, but skip dimming. I add ambient light and name it “kitchen”. I learn “on” and “off”, but skip dimming. The control of the ambient light works.
I restart the computer.
I start AsTeRICS Ergo - the control of the devices works.
I add the remote commands “light on” and “lights of”. It works.
I add the television and can control it.
I delete the button “Volume –“ and add it again. It works.
I restart the PC.
The devices are still there, the control of them works.
I close AsTeRICS Ergo. I unplug the IrTrans. I open AsTeRICS Ergo. The control of the devices is still working.
I delete the device “television” and add it again - now I have every command twice. I delete the device “television” and add it again, but now I name it “TV”. I have every command once.
**I select „New Device“ – „Table / Floor Lamp“ – the lamp is not lit after 10 sec, I choose „solve the problem“, however, the test fails.**
**Kaspersky: I enable the protection
The control of the devices using AsTeRICS Ergo is still working.
I restart the computer.
The control is still working (even though the Kaspersky protection is active).**

**_Summary of positive findings:_**
- **Successful installation of IrTrans after deactivating the Kaspersky protection**
- **After setting up the control of the devices successfully, the control of the devices using AsTeRICS Ergo is possible, even though the Kaspersky protection is enabled.**

_**Errors:**_
- **The installation of the FS20 system remains unsuccessful.**
- **Sometimes already set up devices are gone after restarting the computer.**
- **When deleting a device and adding a new one with the same name, the old commands are still there.**

**Comment by klues** [comment]
Hi, unfortunately you are testing with an old version (sorry that I did not read your tests until now).
* the communication between ARE and webapp has been changed with https://github.com/asterics/AsTeRICS-Ergo/issues/1 so maybe the issue that you have to disable kaspersky is now gone with that.
* the issue that sometimes devices are gone or buttons duplicated i also improved with https://github.com/asterics/AsTeRICS-Ergo/issues/1 so i hope this also should be better
* The error with the FS20 was, that the red light stopped after some time, right? Did you try to use the fix in the FS20-installation-wizard? if yes, what happened there?

**Comment by klues** [comment]
just published a new release including the mentioned fixes: https://github.com/asterics/AsTeRICS-Ergo/releases/tag/v3.2.2
@stefaniehoechtl maybe I should show you some time how you can run the latest version on your computer without installing a new release

**Comment by stefaniehoechtl** [comment]
Yes please, maybe you can show me on Monday?
I did a test with the latest version (see new issue).
