### ISSUE TITLE
Test report AsTeRICS Ergo v-3.2.2 Windows 10 acer

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#43]
Acer - Windows 10
AsTeRICS Ergo Version 3.2.2
When opening the installation file, a window pops up which states that the execution of this app might be a risk for the PC. 
...
I choose “New Device” – “Table / Floor Lamp”. I am asked whether I have already bought the FS20 system - I select yes. **I follow the instructions in the FS20 Installation Wizard. However, the lamp is not lit after 10 sec. When selecting “fix problem”, nothing happens. (I deactivate Kaspersky – restart AsTeRICS Ergo and try again – this does not make any difference.)**
I activate Kaspersky, go back and select “ambient light”. I am asked whether I have already bought the IrTrans. I select “yes”. **I follow the instructions of the IrTrans Installation Wizard. However, the test at the end of the page fails.**
I close IrTrans & AsTeRICS Ergo, unplug the IrTrans, deactivate Kaspersky, uninstall the IRTrans software and restart the computer. I try everything again (“New Device” – “Ambient Light” – following the instructions of the IrTrans Installation Wizard). However, the test fails again.
**I uninstall the IrTrans & AsTeRICS Ergo. I deactivate Kaspersky. I restart the computer and start from the beginning. However, this does not make any difference.**

**Conclusion:**
**-->It is not possible to successfully install the IrTrans & FS20 system.**

**Comment by klues** [comment]
thanks for testing! :)

**regarding (1) - FS20:**
* I also tried it yesterday on win10 and it did not work - we are already investigating this problem in https://github.com/asterics/AsTeRICS-Ergo/issues/21

**regarding (2) - IrTrans:**
* I'll now try it on my computer.

PS: please write tests a little bit more structured like e.g.
**Test 1:**
* Install AsTeRICS-Ergo
* Go to "new Device" -> "Table / Floor Lamp"
* Fs20 not found -> go to FS20 installation wizard
* red lamp turns off -> "click" fix problem
* nothing happens, after re-attatching the red light turns of again and the test is not successful

**Test 2:**
* same steps as Test 1, but Kaspersky deactivated
* no difference - "fix problem" in FS20-wizard does not work

... more Tests

**Conclusion, Problems are:**
* "Fix problem" in FS20-install wizard does not work
* IrTrans-Test on install-wizard fails, although IrServer is running and IrTrans is connected (green light on IrTrans?!)

**Comment by klues** [comment]
such a structured form will help us to more quickly see what is wrong and follow your actions, you did...

**Comment by stefaniehoechtl** [comment]
Ok, I'll try and do it like this next time. ;)
