### ISSUE TITLE
add picture of USB cable in "assistance to IrTrans"

### ISSUE THREAD

**Issue by stefaniehoechtl** [asterics/AsTeRICS-Ergo#5]
**Problem:**
It is not clear that an USB cable is needed to control IR-devices (connection IrTrans - computer).

**Solution:** 
Add a picture of an USB cable (and a plus between the IrTrans and the cable) in “Assistance to IrTrans”.

**Issue resolved if:**
A picture of an USB cable is added in "assistance to IrTrans".

**Comment by klues** [comment]
is now implemented like in the help for Fs20: http://prntscr.com/gi9ggf
see PR https://github.com/asterics/AsTeRICS-Ergo/pull/7
