### ISSUE TITLE
Link AsTeRICS Ergo from www.asterics-academy.net

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Ergo#99]
Add an entry to http://www.asterics-academy.net/tools

and link to the mock version https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home
and the help page directly: https://asterics.github.io/AsTeRICS-Ergo/mock.html#!/home/envcontrol/help

**Comment by klues** [comment]
done: http://www.asterics-academy.net/tools/asterics-ergo
